apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: sns
  labels:
    app: payment
spec:
  selector:
    matchLabels:
      app: payment
  replicas: 1
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: sns-payment:latest
        ports:
        - containerPort: 3000
        env:
          - name: NODE_ENV
            value: "production"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-conf
                key: redis_password
          - name: CONFIG_DIR
            value: "/opt/sns/app/config"
        imagePullPolicy: "Never"
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        livenessProbe:
          httpGet:
            port: 3000
            path: /probes/liveness
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            port: 3000
            path: /probes/readiness
          initialDelaySeconds: 10
          periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: sns
  labels:
    app: payment
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: payment
